### PR TITLE
Incentive done , pdf download issue is resolved

### PR DESCRIPTION
**Pull request by ritik-bizbrolly**
All the incentive related part are done and PDF downloading issue is resolved .

### CODE REVIEW

**Comment by drtechie** [comment]
@ritik-bizbrolly can you mention the rationale for the need for READ_EXTERNAL_STORAGE permission

**Comment by ritik-bizbrolly** [comment]
READ_EXTERNAL_STORAGE is required for downloading(WRITE_EXTERNAL_STORAGE ) and then display it (READ_EXTERNAL_STORAGE).

**Comment by drtechie** [comment]
Where are you saving the downloaded PDF?
If you are downloading to shared folders like Download, this READ permission is not required.
Also what is lowest Android version you are supporting?
You might need it only if < Android 10 is supported.

**Comment by ritik-bizbrolly** [comment]
We are saving pdf in download folder but it is working  without read storage permission in android version 10 and above. But for below  version 10 devices we need read storage permissions.
________________________________

**Review by drtechie — APPROVED** [review]

**Pull request merged**
